# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clock.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import darkdetect


class Ui_ClockWindow(object):


    #====================================Designer codes================================
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(570, 580)
        MainWindow.setMinimumSize(QtCore.QSize(570, 580))
        MainWindow.setMaximumSize(QtCore.QSize(570, 580))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/matin/Desktop/Tools/images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: #F9F9F9;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pages = QtWidgets.QStackedWidget(self.centralwidget)
        self.pages.setGeometry(QtCore.QRect(0, 37, 570, 550))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.pages.setFont(font)
        self.pages.setStyleSheet("border:none;")
        self.pages.setObjectName("pages")
        self.page_alarm = QtWidgets.QWidget()
        self.page_alarm.setObjectName("page_alarm")
        self.frame_2 = QtWidgets.QFrame(self.page_alarm)
        self.frame_2.setGeometry(QtCore.QRect(0, 420, 570, 90))
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.alarm_newbtn = QtWidgets.QPushButton(self.frame_2)
        self.alarm_newbtn.setGeometry(QtCore.QRect(255, 20, 60, 60))
        self.alarm_newbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.alarm_newbtn.setStyleSheet("background-color: #DEDEDE;\n"
"border-radius: 20px;")
        self.alarm_newbtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/home/matin/Desktop/Tools/images/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.alarm_newbtn.setIcon(icon1)
        self.alarm_newbtn.setIconSize(QtCore.QSize(50, 50))
        self.alarm_newbtn.setObjectName("alarm_newbtn")
        self.frame_3 = QtWidgets.QFrame(self.page_alarm)
        self.frame_3.setGeometry(QtCore.QRect(0, 50, 570, 80))
        self.frame_3.setStyleSheet("background: none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(60, 12, 16, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #0B0D12;")
        self.label.setObjectName("label")
        self.alarm_timeleft = QtWidgets.QLabel(self.frame_3)
        self.alarm_timeleft.setGeometry(QtCore.QRect(30, 60, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.alarm_timeleft.setFont(font)
        self.alarm_timeleft.setStyleSheet("color: #0B0D12;")
        self.alarm_timeleft.setObjectName("alarm_timeleft")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setGeometry(QtCore.QRect(453, 24, 91, 41))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.alarm_Bbtn1 = QtWidgets.QLabel(self.frame_5)
        self.alarm_Bbtn1.setGeometry(QtCore.QRect(20, 10, 50, 20))
        self.alarm_Bbtn1.setStyleSheet("background-color: #DEDEDE;\n"
"border-radius: 10px;")
        self.alarm_Bbtn1.setText("")
        self.alarm_Bbtn1.setObjectName("alarm_Bbtn1")
        self.alarm_btn1 = QtWidgets.QLabel(self.frame_5)
        self.alarm_btn1.setGeometry(QtCore.QRect(23, 12, 20, 16))
        self.alarm_btn1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.alarm_btn1.setStyleSheet("border-radius: 7px;\n"
"background-color: #b5b5b5;")
        self.alarm_btn1.setText("")
        self.alarm_btn1.setObjectName("alarm_btn1")
        self.alarm_hour1 = QtWidgets.QLabel(self.frame_3)
        self.alarm_hour1.setGeometry(QtCore.QRect(20, 13, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(13)
        self.alarm_hour1.setFont(font)
        self.alarm_hour1.setStyleSheet("color: #0B0D12;")
        self.alarm_hour1.setAlignment(QtCore.Qt.AlignCenter)
        self.alarm_hour1.setObjectName("alarm_hour1")
        self.alarm_min1 = QtWidgets.QLabel(self.frame_3)
        self.alarm_min1.setGeometry(QtCore.QRect(65, 13, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(13)
        self.alarm_min1.setFont(font)
        self.alarm_min1.setStyleSheet("color: #0B0D12;")
        self.alarm_min1.setAlignment(QtCore.Qt.AlignCenter)
        self.alarm_min1.setObjectName("alarm_min1")
        self.alarm_deletebtn1 = QtWidgets.QPushButton(self.frame_3)
        self.alarm_deletebtn1.setGeometry(QtCore.QRect(525, 23, 30, 41))
        self.alarm_deletebtn1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.alarm_deletebtn1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/home/matin/Desktop/Tools/images/delete-bin-dark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.alarm_deletebtn1.setIcon(icon2)
        self.alarm_deletebtn1.setIconSize(QtCore.QSize(20, 20))
        self.alarm_deletebtn1.setObjectName("alarm_deletebtn1")
        self.frame_4 = QtWidgets.QFrame(self.page_alarm)
        self.frame_4.setGeometry(QtCore.QRect(0, 160, 570, 80))
        self.frame_4.setStyleSheet("background: none;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(60, 12, 16, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #0B0D12;")
        self.label_2.setObjectName("label_2")
        self.alarm_timeleft_2 = QtWidgets.QLabel(self.frame_4)
        self.alarm_timeleft_2.setGeometry(QtCore.QRect(30, 60, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.alarm_timeleft_2.setFont(font)
        self.alarm_timeleft_2.setStyleSheet("color: #0B0D12;")
        self.alarm_timeleft_2.setObjectName("alarm_timeleft_2")
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setGeometry(QtCore.QRect(453, 24, 91, 41))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.alarm_btn1_3 = QtWidgets.QLabel(self.frame_7)
        self.alarm_btn1_3.setGeometry(QtCore.QRect(20, 10, 50, 20))
        self.alarm_btn1_3.setStyleSheet("background-color: #3CB9C9;\n"
"border-radius: 10px;")
        self.alarm_btn1_3.setText("")
        self.alarm_btn1_3.setObjectName("alarm_btn1_3")
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        self.label_7.setGeometry(QtCore.QRect(47, 12, 20, 16))
        self.label_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_7.setStyleSheet("border-radius: 7px;\n"
"background-color: #DEDEDE;")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.alarm_hour_3 = QtWidgets.QLabel(self.frame_4)
        self.alarm_hour_3.setGeometry(QtCore.QRect(20, 13, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(13)
        self.alarm_hour_3.setFont(font)
        self.alarm_hour_3.setStyleSheet("color: #0B0D12;")
        self.alarm_hour_3.setAlignment(QtCore.Qt.AlignCenter)
        self.alarm_hour_3.setObjectName("alarm_hour_3")
        self.alarm_min_3 = QtWidgets.QLabel(self.frame_4)
        self.alarm_min_3.setGeometry(QtCore.QRect(65, 13, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(13)
        self.alarm_min_3.setFont(font)
        self.alarm_min_3.setStyleSheet("color: #0B0D12;")
        self.alarm_min_3.setAlignment(QtCore.Qt.AlignCenter)
        self.alarm_min_3.setObjectName("alarm_min_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setGeometry(QtCore.QRect(525, 23, 30, 41))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setText("")
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pages.addWidget(self.page_alarm)
        self.page_timer = QtWidgets.QWidget()
        self.page_timer.setObjectName("page_timer")
        self.timer_Cleft = QtWidgets.QFrame(self.page_timer)
        self.timer_Cleft.setGeometry(QtCore.QRect(135, 50, 300, 300))
        self.timer_Cleft.setStyleSheet("QFrame{\n"
"    border-radius: 150px;\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.748 rgba(85, 87, 83, 0), stop:0.749 rgba(60, 185, 201, 255));\n"
"}")
        self.timer_Cleft.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.timer_Cleft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.timer_Cleft.setObjectName("timer_Cleft")
        self.frame_8 = QtWidgets.QFrame(self.timer_Cleft)
        self.frame_8.setGeometry(QtCore.QRect(20, 20, 260, 260))
        self.frame_8.setStyleSheet("background-color: #F9F9F9;\n"
"border-radius: 130px;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.layoutWidget = QtWidgets.QWidget(self.frame_8)
        self.layoutWidget.setGeometry(QtCore.QRect(77, 99, 113, 65))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.timer_timeleft = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sawasdee")
        font.setPointSize(30)
        self.timer_timeleft.setFont(font)
        self.timer_timeleft.setStyleSheet("color: #0B0D12;")
        self.timer_timeleft.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_timeleft.setObjectName("timer_timeleft")
        self.verticalLayout.addWidget(self.timer_timeleft)
        self.timer_totaltime = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.timer_totaltime.setFont(font)
        self.timer_totaltime.setStyleSheet("color: #0B0D12;")
        self.timer_totaltime.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_totaltime.setObjectName("timer_totaltime")
        self.verticalLayout.addWidget(self.timer_totaltime)
        self.timer_Cleft_2 = QtWidgets.QFrame(self.page_timer)
        self.timer_Cleft_2.setGeometry(QtCore.QRect(135, 50, 300, 300))
        self.timer_Cleft_2.setStyleSheet("QFrame{\n"
"    border-radius: 150px;\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.000 rgba(85, 87, 83, 0), stop:0.000 rgba(222, 222, 222, 255));\n"
"}")
        self.timer_Cleft_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.timer_Cleft_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.timer_Cleft_2.setObjectName("timer_Cleft_2")
        self.frame_9 = QtWidgets.QFrame(self.page_timer)
        self.frame_9.setGeometry(QtCore.QRect(0, 420, 570, 90))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.timer_stopbtn = QtWidgets.QPushButton(self.frame_9)
        self.timer_stopbtn.setGeometry(QtCore.QRect(205, 20, 60, 60))
        self.timer_stopbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.timer_stopbtn.setStyleSheet("background-color: #DEDEDE;\n"
"border-radius: 20px;")
        self.timer_stopbtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("/home/matin/Desktop/Tools/images/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.timer_stopbtn.setIcon(icon3)
        self.timer_stopbtn.setIconSize(QtCore.QSize(50, 50))
        self.timer_stopbtn.setObjectName("timer_stopbtn")
        self.timer_pausebtn = QtWidgets.QPushButton(self.frame_9)
        self.timer_pausebtn.setGeometry(QtCore.QRect(305, 20, 60, 60))
        self.timer_pausebtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.timer_pausebtn.setStyleSheet("background-color: #DEDEDE;\n"
"border-radius: 20px;")
        self.timer_pausebtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("/home/matin/Desktop/Tools/images/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.timer_pausebtn.setIcon(icon4)
        self.timer_pausebtn.setIconSize(QtCore.QSize(50, 50))
        self.timer_pausebtn.setObjectName("timer_pausebtn")
        self.timer_Cleft_2.raise_()
        self.timer_Cleft.raise_()
        self.frame_9.raise_()
        self.pages.addWidget(self.page_timer)
        self.page_stopwatch = QtWidgets.QWidget()
        self.page_stopwatch.setObjectName("page_stopwatch")
        self.frame_10 = QtWidgets.QFrame(self.page_stopwatch)
        self.frame_10.setGeometry(QtCore.QRect(157, 120, 256, 74))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stop_hour = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Sawasdee")
        font.setPointSize(30)
        self.stop_hour.setFont(font)
        self.stop_hour.setStyleSheet("color: #0B0D12;")
        self.stop_hour.setAlignment(QtCore.Qt.AlignCenter)
        self.stop_hour.setObjectName("stop_hour")
        self.horizontalLayout.addWidget(self.stop_hour)
        self.label_8 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Sawasdee")
        font.setPointSize(30)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: #0B0D12;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.stop_min = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Sawasdee")
        font.setPointSize(30)
        self.stop_min.setFont(font)
        self.stop_min.setStyleSheet("color: #0B0D12;")
        self.stop_min.setAlignment(QtCore.Qt.AlignCenter)
        self.stop_min.setObjectName("stop_min")
        self.horizontalLayout.addWidget(self.stop_min)
        self.label_10 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Sawasdee")
        font.setPointSize(30)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: #0B0D12;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.stop_sec = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Sawasdee")
        font.setPointSize(30)
        self.stop_sec.setFont(font)
        self.stop_sec.setStyleSheet("color: #0B0D12;")
        self.stop_sec.setAlignment(QtCore.Qt.AlignCenter)
        self.stop_sec.setObjectName("stop_sec")
        self.horizontalLayout.addWidget(self.stop_sec)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.frame_11 = QtWidgets.QFrame(self.page_stopwatch)
        self.frame_11.setGeometry(QtCore.QRect(0, 420, 570, 90))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.stop_stopbtn = QtWidgets.QPushButton(self.frame_11)
        self.stop_stopbtn.setGeometry(QtCore.QRect(205, 20, 60, 60))
        self.stop_stopbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stop_stopbtn.setStyleSheet("background-color: #DEDEDE;\n"
"border-radius: 20px;")
        self.stop_stopbtn.setText("")
        self.stop_stopbtn.setIcon(icon3)
        self.stop_stopbtn.setIconSize(QtCore.QSize(50, 50))
        self.stop_stopbtn.setObjectName("stop_stopbtn")
        self.stop_flagbtn = QtWidgets.QPushButton(self.frame_11)
        self.stop_flagbtn.setGeometry(QtCore.QRect(305, 20, 60, 60))
        self.stop_flagbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stop_flagbtn.setStyleSheet("background-color: #DEDEDE;\n"
"border-radius: 20px;")
        self.stop_flagbtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("/home/matin/Desktop/Tools/images/flag-time.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_flagbtn.setIcon(icon5)
        self.stop_flagbtn.setIconSize(QtCore.QSize(50, 50))
        self.stop_flagbtn.setObjectName("stop_flagbtn")
        self.frame_12 = QtWidgets.QFrame(self.page_stopwatch)
        self.frame_12.setGeometry(QtCore.QRect(80, 230, 400, 150))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.stop_F1 = QtWidgets.QLabel(self.frame_12)
        self.stop_F1.setGeometry(QtCore.QRect(0, 0, 400, 17))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        self.stop_F1.setFont(font)
        self.stop_F1.setStyleSheet("color: #0B0D12;")
        self.stop_F1.setAlignment(QtCore.Qt.AlignCenter)
        self.stop_F1.setObjectName("stop_F1")
        self.stop_F2 = QtWidgets.QLabel(self.frame_12)
        self.stop_F2.setGeometry(QtCore.QRect(0, 40, 400, 17))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        self.stop_F2.setFont(font)
        self.stop_F2.setStyleSheet("color: #0B0D12;")
        self.stop_F2.setAlignment(QtCore.Qt.AlignCenter)
        self.stop_F2.setObjectName("stop_F2")
        self.stop_F3 = QtWidgets.QLabel(self.frame_12)
        self.stop_F3.setGeometry(QtCore.QRect(0, 80, 400, 17))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        self.stop_F3.setFont(font)
        self.stop_F3.setStyleSheet("color: #0B0D12;")
        self.stop_F3.setAlignment(QtCore.Qt.AlignCenter)
        self.stop_F3.setObjectName("stop_F3")
        self.stop_F4 = QtWidgets.QLabel(self.frame_12)
        self.stop_F4.setGeometry(QtCore.QRect(0, 120, 400, 17))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        self.stop_F4.setFont(font)
        self.stop_F4.setStyleSheet("color: #0B0D12;")
        self.stop_F4.setAlignment(QtCore.Qt.AlignCenter)
        self.stop_F4.setObjectName("stop_F4")
        self.pages.addWidget(self.page_stopwatch)
        self.page_world = QtWidgets.QWidget()
        self.page_world.setObjectName("page_world")
        self.world_selectCity = QtWidgets.QComboBox(self.page_world)
        self.world_selectCity.setGeometry(QtCore.QRect(170, 140, 230, 40))
        self.world_selectCity.setStyleSheet("background: #DEDEDE;\n"
"color: #0B0D12;\n"
"border-radius: 10px;")
        self.world_selectCity.setObjectName("world_selectCity")
        self.world_selectCity.addItem("")
        self.world_selectCity.addItem("")
        self.world_city = QtWidgets.QLabel(self.page_world)
        self.world_city.setGeometry(QtCore.QRect(0, 230, 570, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(13)
        self.world_city.setFont(font)
        self.world_city.setStyleSheet("color: #0B0D12;")
        self.world_city.setAlignment(QtCore.Qt.AlignCenter)
        self.world_city.setObjectName("world_city")
        self.world_cityTime = QtWidgets.QLabel(self.page_world)
        self.world_cityTime.setGeometry(QtCore.QRect(0, 260, 570, 51))
        font = QtGui.QFont()
        font.setFamily("Sawasdee")
        font.setPointSize(30)
        self.world_cityTime.setFont(font)
        self.world_cityTime.setStyleSheet("color: #0B0D12;")
        self.world_cityTime.setAlignment(QtCore.Qt.AlignCenter)
        self.world_cityTime.setObjectName("world_cityTime")
        self.pages.addWidget(self.page_world)
        self.page_settings = QtWidgets.QWidget()
        self.page_settings.setObjectName("page_settings")
        self.label_3 = QtWidgets.QLabel(self.page_settings)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 251, 50))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #0B0D12;")
        self.label_3.setObjectName("label_3")
        self.frame_6 = QtWidgets.QFrame(self.page_settings)
        self.frame_6.setGeometry(QtCore.QRect(20, 130, 60, 60))
        self.frame_6.setStyleSheet("background-color: #DEDEDE;\n"
"border-radius: 20px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.settings_btndark = QtWidgets.QPushButton(self.frame_6)
        self.settings_btndark.setGeometry(QtCore.QRect(10, 10, 40, 40))
        self.settings_btndark.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settings_btndark.setStyleSheet("background-color: #0B0D12;\n"
"border-radius: 15px;")
        self.settings_btndark.setText("")
        self.settings_btndark.setObjectName("settings_btndark")
        self.frame_13 = QtWidgets.QFrame(self.page_settings)
        self.frame_13.setGeometry(QtCore.QRect(130, 130, 60, 60))
        self.frame_13.setStyleSheet("background-color: #DEDEDE;\n"
"border-radius: 20px;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.settings_btnlight = QtWidgets.QPushButton(self.frame_13)
        self.settings_btnlight.setGeometry(QtCore.QRect(10, 10, 40, 40))
        self.settings_btnlight.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settings_btnlight.setStyleSheet("background-color: #F9F9F9;\n"
"border-radius: 15px;")
        self.settings_btnlight.setText("")
        self.settings_btnlight.setObjectName("settings_btnlight")
        self.frame_14 = QtWidgets.QFrame(self.page_settings)
        self.frame_14.setGeometry(QtCore.QRect(240, 130, 60, 60))
        self.frame_14.setStyleSheet("background-color: #DEDEDE;\n"
"border-radius: 20px;")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.settings_btndef = QtWidgets.QPushButton(self.frame_14)
        self.settings_btndef.setGeometry(QtCore.QRect(10, 10, 40, 40))
        self.settings_btndef.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settings_btndef.setStyleSheet("background-color: #0B0D12;\n"
"border-radius: 15px;")
        self.settings_btndef.setText("")
        self.settings_btndef.setObjectName("settings_btndef")
        self.label_5 = QtWidgets.QLabel(self.page_settings)
        self.label_5.setGeometry(QtCore.QRect(20, 200, 60, 17))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #0B0D12;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page_settings)
        self.label_6.setGeometry(QtCore.QRect(130, 200, 60, 17))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: #0B0D12;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_11 = QtWidgets.QLabel(self.page_settings)
        self.label_11.setGeometry(QtCore.QRect(220, 200, 100, 17))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: #0B0D12;")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.page_settings)
        self.label_12.setGeometry(QtCore.QRect(20, 270, 251, 50))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: #0B0D12;")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.page_settings)
        self.label_13.setGeometry(QtCore.QRect(20, 320, 511, 181))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: #0B0D12;")
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.pages.addWidget(self.page_settings)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 570, 50))
        self.frame.setStyleSheet("background: none;\n"
"border: none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_alarm = QtWidgets.QPushButton(self.frame)
        self.btn_alarm.setGeometry(QtCore.QRect(0, 0, 132, 50))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.btn_alarm.setFont(font)
        self.btn_alarm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_alarm.setStyleSheet("border-right: 1px solid rgb(11, 13, 18);\n"
"background-color: #F9F9F9;\n"
"color: #0B0D12;")
        self.btn_alarm.setObjectName("btn_alarm")
        self.btn_timer = QtWidgets.QPushButton(self.frame)
        self.btn_timer.setGeometry(QtCore.QRect(132, 0, 132, 50))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.btn_timer.setFont(font)
        self.btn_timer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_timer.setStyleSheet("border-right: 1px solid rgb(11, 13, 18);\n"
"background-color: #DEDEDE;\n"
"color: #0B0D12;")
        self.btn_timer.setObjectName("btn_timer")
        self.btn_stopW = QtWidgets.QPushButton(self.frame)
        self.btn_stopW.setGeometry(QtCore.QRect(264, 0, 132, 50))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.btn_stopW.setFont(font)
        self.btn_stopW.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_stopW.setStyleSheet("border-right: 1px solid rgb(11, 13, 18);\n"
"background-color: #DEDEDE;\n"
"color: #0B0D12;")
        self.btn_stopW.setObjectName("btn_stopW")
        self.btn_world = QtWidgets.QPushButton(self.frame)
        self.btn_world.setGeometry(QtCore.QRect(396, 0, 132, 50))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.btn_world.setFont(font)
        self.btn_world.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_world.setStyleSheet("border-right: 1px solid rgb(11, 13, 18);\n"
"background-color: #DEDEDE;\n"
"color: #0B0D12;")
        self.btn_world.setObjectName("btn_world")
        self.btn_settings = QtWidgets.QPushButton(self.frame)
        self.btn_settings.setGeometry(QtCore.QRect(528, 0, 42, 50))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.btn_settings.setFont(font)
        self.btn_settings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_settings.setStyleSheet("border-right: 1px solid rgba(222, 222, 222, 0.6);\n"
"background-color: #DEDEDE;")
        self.btn_settings.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("/home/matin/Desktop/Tools/images/settings-dark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_settings.setIcon(icon6)
        self.btn_settings.setIconSize(QtCore.QSize(20, 20))
        self.btn_settings.setObjectName("btn_settings")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



        #------------------------------------My codes--------------------------

        # delete some objects
        self.frame_4.deleteLater()
        self.stop_F1.deleteLater()
        self.stop_F2.deleteLater()
        self.stop_F3.deleteLater()
        self.stop_F4.deleteLater()

        # related to themes
        self.defualt_counter = 0

        self.defualt_theme = darkdetect.theme()
        if self.defualt_theme == 'Dark':
            self.btn_alarm.setStyleSheet('border-right: 1px solid rgb(11, 13, 18);background-color: #0B0D12;color: #F9F9F9;')

        self.setColor('def')

        self.settings_btndef.clicked.connect(lambda: self.setColor('def'))
        self.settings_btndark.clicked.connect(lambda: self.setColor('Dark'))
        self.settings_btnlight.clicked.connect(lambda: self.setColor('Light'))



    #-------------------------Designer codes------------------------------------
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tools"))
        self.label.setText(_translate("MainWindow", ":"))
        self.alarm_timeleft.setText(_translate("MainWindow", "Alarm in 6 hours and 30 minutes"))
        self.alarm_hour1.setText(_translate("MainWindow", "00"))
        self.alarm_min1.setText(_translate("MainWindow", "00"))
        self.label_2.setText(_translate("MainWindow", ":"))
        self.alarm_timeleft_2.setText(_translate("MainWindow", "Alarm in 6 hours and 30 minutes"))
        self.alarm_hour_3.setText(_translate("MainWindow", "00"))
        self.alarm_min_3.setText(_translate("MainWindow", "00"))
        self.timer_timeleft.setText(_translate("MainWindow", "13"))
        self.timer_totaltime.setText(_translate("MainWindow", "Total 50 seconds"))
        self.stop_hour.setText(_translate("MainWindow", "00"))
        self.label_8.setText(_translate("MainWindow", ":"))
        self.stop_min.setText(_translate("MainWindow", "02"))
        self.label_10.setText(_translate("MainWindow", ":"))
        self.stop_sec.setText(_translate("MainWindow", "12"))
        self.stop_F1.setText(_translate("MainWindow", "00:00:24"))
        self.stop_F2.setText(_translate("MainWindow", "00:01:02"))
        self.stop_F3.setText(_translate("MainWindow", "00:02:05"))
        self.stop_F4.setText(_translate("MainWindow", "00:02:06"))
        self.world_selectCity.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.world_selectCity.setItemText(0, _translate("MainWindow", "Asia/Tehran"))
        self.world_selectCity.setItemText(1, _translate("MainWindow", "America/New_York"))
        self.world_city.setText(_translate("MainWindow", "Tehran"))
        self.world_cityTime.setText(_translate("MainWindow", "22:33"))
        self.label_3.setText(_translate("MainWindow", "Select app theme"))
        self.label_5.setText(_translate("MainWindow", "Dark"))
        self.label_6.setText(_translate("MainWindow", "Light"))
        self.label_11.setText(_translate("MainWindow", "System default"))
        self.label_12.setText(_translate("MainWindow", "About"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p>This is a multifunctional app that helps you do your daily activities better.</p><p>This app programmed by a 15-year-old teenager who is interested in programming.</p><p>So you can support him with this links:</p><p>GitHub: <a href=\"https://github.com/Matin-Ardestani\"><span style=\" text-decoration: underline; color:#0000ff;\">github.com/Matin-Ardestani</span></a></p><p>Social medeia: <a href=\"https://bioly.io/MatinArdestani\"><span style=\" text-decoration: underline; color:#0000ff;\">bioly.io/MatinArdestani</span></a></p></body></html>"))
        self.btn_alarm.setText(_translate("MainWindow", "Alarm"))
        self.btn_timer.setText(_translate("MainWindow", "Timer"))
        self.btn_stopW.setText(_translate("MainWindow", "StopWatch"))
        self.btn_world.setText(_translate("MainWindow", "WorldClock"))

    # ==================================My codes=========================
    def setColor(self , theme):

        def dark_colors():
            # moving between pages
            icon_light = QtGui.QIcon()
            icon_light.addPixmap(QtGui.QPixmap("/home/matin/Desktop/Tools/images/settings-light.png"),    QtGui.QIcon.Normal, QtGui.QIcon.Off)

            icon_dark = QtGui.QIcon()
            icon_dark.addPixmap(QtGui.QPixmap("/home/matin/Desktop/Tools/images/settings-dark.png"),    QtGui.QIcon.Normal, QtGui.QIcon.Off)

            self.btn_alarm.clicked.connect(lambda: [self.pages.setCurrentWidget(self.page_alarm) , 
            self.btn_alarm.setStyleSheet('background-color: #0B0D12; border-right: 1px solid #0B0D12;    color: #F9F9F9;'),
            self.btn_timer.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color: #0B0D12'),
            self.btn_stopW.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color: #0B0D12'),
            self.btn_world.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color: #0B0D12'),
            self.btn_settings.setStyleSheet('background-color: #DEDEDE;'),
            self.btn_settings.setIcon(icon_dark)
            ])

            self.btn_timer.clicked.connect(lambda: [self.pages.setCurrentWidget(self.page_timer) , 
            self.btn_timer.setStyleSheet('background-color: #0B0D12; border-right: 1px solid #0B0D12;    color: #F9F9F9;'),
            self.btn_alarm.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color: #0B0D12'),
            self.btn_stopW.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color: #0B0D12'),
            self.btn_world.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color: #0B0D12'),
            self.btn_settings.setStyleSheet('background-color: #DEDEDE;'),
            self.btn_settings.setIcon(icon_dark)
            ])

            self.btn_stopW.clicked.connect(lambda: [self.pages.setCurrentWidget(self.page_stopwatch) , 
            self.btn_stopW.setStyleSheet('background-color: #0B0D12; border-right: 1px solid #0B0D12;    color: #F9F9F9;'),
            self.btn_timer.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color: #0B0D12'),
            self.btn_alarm.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color: #0B0D12'),
            self.btn_world.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color: #0B0D12'),
            self.btn_settings.setStyleSheet('background-color: #DEDEDE;'),
            self.btn_settings.setIcon(icon_dark)
            ])

            self.btn_world.clicked.connect(lambda: [self.pages.setCurrentWidget(self.page_world) , 
            self.btn_world.setStyleSheet('background-color: #0B0D12; border-right: 1px solid #0B0D12;    color: #F9F9F9;'),
            self.btn_timer.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color: #0B0D12'),
            self.btn_stopW.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color: #0B0D12'),
            self.btn_alarm.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color: #0B0D12'),
            self.btn_settings.setStyleSheet('background-color: #DEDEDE;'),
            self.btn_settings.setIcon(icon_dark)
            ])

            self.btn_settings.clicked.connect(lambda: [self.pages.setCurrentWidget(self.page_settings) , 
            self.btn_settings.setStyleSheet('background-color: #0B0D12;'),
            self.btn_settings.setIcon(icon_light),
            self.btn_timer.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color: #0B0D12'),
            self.btn_stopW.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color: #0B0D12'),
            self.btn_world.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color: #0B0D12'),
            self.btn_alarm.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;')
            ])

            # alarm page
            self.page_alarm.setStyleSheet('border:none; background-color: #0B0D12;')
            self.alarm_hour1.setStyleSheet('color: #F9F9F9;')
            self.alarm_min1.setStyleSheet('color: #F9F9F9;')
            self.label.setStyleSheet('color: #F9F9F9;')
            self.alarm_timeleft.setStyleSheet('color: #F9F9F9;')

            # timer page
            self.page_timer.setStyleSheet('border:none; background-color: #0B0D12;')
            self.frame_8.setStyleSheet('background-color: #0B0D12; border-radius: 130px;')
            self.timer_timeleft.setStyleSheet('color: #F9F9F9;')
            self.timer_totaltime.setStyleSheet('color: #F9F9F9;')

            # stopwatch page
            self.page_stopwatch.setStyleSheet('border:none; background-color: #0B0D12;')
            self.stop_hour.setStyleSheet('color: #F9F9F9;')
            self.stop_min.setStyleSheet('color: #F9F9F9;')
            self.stop_sec.setStyleSheet('color: #F9F9F9;')
            self.label_8.setStyleSheet('color: #F9F9F9;')
            self.label_10.setStyleSheet('color: #F9F9F9;')


            # worldtime page
            self.page_world.setStyleSheet('border:none; background-color: #0B0D12;')
            self.world_city.setStyleSheet('color: #F9F9F9;')
            self.world_cityTime.setStyleSheet('color: #F9F9F9;')

            # settings page
            self.page_settings.setStyleSheet('border:none; background-color: #0B0D12;')
            self.label_3.setStyleSheet('color: #F9F9F9;')
            self.label_5.setStyleSheet('color: #F9F9F9;')
            self.label_6.setStyleSheet('color: #F9F9F9;')
            self.label_11.setStyleSheet('color: #F9F9F9;')
            self.label_12.setStyleSheet('color: #F9F9F9;')
            self.label_13.setStyleSheet('color: #F9F9F9;')

        def light_colors():
            # moving between pages

            icon_dark = QtGui.QIcon()
            icon_dark.addPixmap(QtGui.QPixmap("/home/matin/Desktop/Tools/images/settings-dark.png"),    QtGui.QIcon.Normal, QtGui.QIcon.Off)

            self.btn_alarm.clicked.connect(lambda: [self.pages.setCurrentWidget(self.page_alarm) , 
            self.btn_alarm.setStyleSheet('background-color: #F9F9F9; border-right: 1px solid #0B0D12'),
            self.btn_timer.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color:     #0B0D12'),
            self.btn_stopW.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color:     #0B0D12'),
            self.btn_world.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color:     #0B0D12'),
            self.btn_settings.setStyleSheet('background-color: #DEDEDE;')
            ])

            self.btn_timer.clicked.connect(lambda: [self.pages.setCurrentWidget(self.page_timer) , 
            self.btn_timer.setStyleSheet('background-color: #F9F9F9; border-right: 1px solid #0B0D12'),
            self.btn_alarm.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color:     #0B0D12'),
            self.btn_stopW.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color:     #0B0D12'),
            self.btn_world.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color:     #0B0D12'),
            self.btn_settings.setStyleSheet('background-color: #DEDEDE;')
            ])

            self.btn_stopW.clicked.connect(lambda: [self.pages.setCurrentWidget(self.page_stopwatch) , 
            self.btn_stopW.setStyleSheet('background-color: #F9F9F9; border-right: 1px solid #0B0D12'),
            self.btn_timer.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color:     #0B0D12'),
            self.btn_alarm.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color:     #0B0D12'),
            self.btn_world.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color:     #0B0D12'),
            self.btn_settings.setStyleSheet('background-color: #DEDEDE;')
            ])

            self.btn_world.clicked.connect(lambda: [self.pages.setCurrentWidget(self.page_world) , 
            self.btn_world.setStyleSheet('background-color: #F9F9F9; border-right: 1px solid #0B0D12'),
            self.btn_timer.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color:     #0B0D12'),
            self.btn_stopW.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color:     #0B0D12'),
            self.btn_alarm.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color:     #0B0D12'),
            self.btn_settings.setStyleSheet('background-color: #DEDEDE;')
            ])

            self.btn_settings.clicked.connect(lambda: [self.pages.setCurrentWidget(self.page_settings) , 
            self.btn_settings.setStyleSheet('background-color: #F9F9F9;'),
            self.btn_timer.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color:     #0B0D12'),
            self.btn_stopW.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color:     #0B0D12'),
            self.btn_world.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;    color:     #0B0D12'),
            self.btn_alarm.setStyleSheet('border-right: 1px solid #0B0D12; background-color: #DEDEDE;'),
            self.btn_settings.setIcon(icon_dark)
            ])

            # page alarm
            self.page_alarm.setStyleSheet('background-color: #F9F9F9; border: none;')
            self.alarm_hour1.setStyleSheet('color: #0B0D12;')
            self.alarm_min1.setStyleSheet('color: #0B0D12;')
            self.label.setStyleSheet('color: #0B0D12;')
            self.alarm_timeleft.setStyleSheet('color: #0B0D12;')

            # page timer
            self.page_timer.setStyleSheet('background-color: #F9F9F9; border: none;')
            self.frame_8.setStyleSheet('background-color: #F9F9F9;border-radius: 130px;')
            self.timer_timeleft.setStyleSheet('color: #0B0D12;')
            self.timer_totaltime.setStyleSheet('color: #0B0D12;')

            # page stopwatch
            self.page_stopwatch.setStyleSheet('background-color: #F9F9F9; border: none;')
            self.stop_hour.setStyleSheet('color: #0B0D12;')
            self.stop_min.setStyleSheet('color: #0B0D12;')
            self.stop_sec.setStyleSheet('color: #0B0D12;')
            self.label_8.setStyleSheet('color: #0B0D12;')
            self.label_10.setStyleSheet('color: #0B0D12;')

            # page worldtime
            self.page_world.setStyleSheet('background-color: #F9F9F9; border: none;')
            self.world_city.setStyleSheet('color: #0B0D12;')
            self.world_cityTime.setStyleSheet('color: #0B0D12;')

            # page settigns
            self.page_settings.setStyleSheet('background-color: #F9F9F9; border: none;')
            self.label_3.setStyleSheet('color: #0B0D12;')
            self.label_5.setStyleSheet('color: #0B0D12;')
            self.label_6.setStyleSheet('color: #0B0D12;')
            self.label_11.setStyleSheet('color: #0B0D12;')
            self.label_12.setStyleSheet('color: #0B0D12;')
            self.label_13.setStyleSheet('color: #0B0D12;')

        if theme == 'def':
            self.defualt_counter += 1
            if self.defualt_theme == 'Dark':
                dark_colors()
                if self.defualt_counter > 1:
                    self.btn_settings.setStyleSheet('background-color: #0B0D12;')
                    icon_dark = QtGui.QIcon()
                    icon_dark.addPixmap(QtGui.QPixmap("/home/matin/Desktop/Tools/images/settings-light.png"),QtGui.QIcon.Normal, QtGui.QIcon.Off)
                    self.btn_settings.setIcon(icon_dark)
            elif self.defualt_theme == 'Light':
                light_colors()
                self.settings_btndef.setStyleSheet('background-color: #F9F9F9;border-radius: 15px;')
                if self.defualt_counter > 1:
                    self.btn_settings.setStyleSheet('background-color: #F9F9F9;')
                    icon_light = QtGui.QIcon()
                    icon_light.addPixmap(QtGui.QPixmap("/home/matin/Desktop/Tools/images/settings-dark.png"),QtGui.QIcon.Normal, QtGui.QIcon.Off)
                    self.btn_settings.setIcon(icon_light)


        elif theme == 'Dark':
            dark_colors()
            self.btn_settings.setStyleSheet('background-color: #0B0D12;')
            icon_light = QtGui.QIcon()
            icon_light.addPixmap(QtGui.QPixmap("/home/matin/Desktop/Tools/images/settings-light.png"),    QtGui.QIcon.Normal, QtGui.QIcon.Off)
            self.btn_settings.setIcon(icon_light)

        elif theme == 'Light':
            light_colors()
            self.btn_settings.setStyleSheet('background-color: #F9F9F9;')
            icon_dark = QtGui.QIcon()
            icon_dark.addPixmap(QtGui.QPixmap("/home/matin/Desktop/Tools/images/settings-dark.png"),    QtGui.QIcon.Normal, QtGui.QIcon.Off)
            self.btn_settings.setIcon(icon_dark)
